apiVersion: v1
kind: Service
metadata:
  name: nginx-project
  namespace: missael
spec:
  selector:
    app: nginx-project
  ports:
    - port: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
  namespace: missael
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
