name: Release Docker Images and upload to ECR

on: push

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-and-upload-app:
    name: Build and Upload to ECR APP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloudengineer-project
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::734647218919:role/github-infrastructure-hire-project-ecr-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Build, tag, and push docker image to Amazon ECR
        working-directory:
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: missael-hire-project
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f flask/app/Dockerfile . -t missael-hire-project:latest 734647218919.dkr.ecr.us-east-1.amazonaws.com/missael-hire-project:latest
        #  docker push 734647218919.dkr.ecr.us-east-1.amazonaws.com/missael-hire-project:latest
